# UI
ui <- fluidPage(
  #includeCSS("www/custom.css"),
  titlePanel(title = 'Indicadores Macroeconómicos'),
  navlistPanel(
    id = "tabset",
    widths = c(2,10),
    fluid = 'TRUE',
    tabPanel('República Dominicana', 
             fluidPage(
               h3('Precios'),
               tags$div(class = 'eco-graphs',
                        h5('Índice de Precios al Consumidor'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('dom_inf'))),
               hr(),
               h3('Actividad Económica'),
               tags$div(class = 'eco-graphs',
                        h5('Índice Mensual de Actividad Económica'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('dom_imae')),
                        fluidRow(column(width = 6,
                                        h5('Producto Interno Bruto'),
                                        p('Variaciones (%)'),
                                        pibUI('dom_pib')),
                                 column(width = 6,
                                        h5('Composición del PIB'),
                                        p(''),
                                        pib_pieUI('dom_pie'))
                                 )
                        ),
               hr(),
               h3('Sector Externo'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tipo de Cambio Venta Nominal'),
                                 p('Variaciones (%)'),
                                 tcUI('dom_tcn')),
                          column(width = 6,
                                 h5('Remesas'),
                                 p('Millones de USD$, Variaciones (%)'),
                                 tcUI('dom_remi'))
                 )
               ),
               hr(),
               h3('Sector Financiero'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tasas de Interés'),
                                 p('(%)'),
                                 fluidRow(tiUI('dom_ti'))),
                          column(width = 6,
                                 h5('Inversión Extranjera Directa'),
                                 p('Millones de USD$'),
                                 fluidRow(iedUI('dom_ied'))))
               ),
             )),
    tabPanel('Costa Rica', 
             fluidPage(
               h3('Precios'),
               tags$div(class = 'eco-graphs',
                        h5('Índice de Precios al Consumidor'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('cri_inf'))),
               hr(),
               h3('Actividad Económica'),
               tags$div(class = 'eco-graphs',
                        h5('Índice Mensual de Actividad Económica'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('cri_imae')),
                        fluidRow(column(width = 6,
                                        h5('Producto Interno Bruto'),
                                        p('Variaciones (%)'),
                                        pibUI('cri_pib')),
                                 column(width = 6,
                                        h5('Composición del PIB'),
                                        p(''),
                                        pib_pieUI('cri_pie'))
                        )
               ),
               hr(),
               h3('Sector Externo'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tipo de Cambio Venta Nominal'),
                                 p('Variaciones (%)'),
                                 tcUI('cri_tcn')),
                          column(width = 6,
                                 h5('Remesas'),
                                 p('Millones de USD$, Variaciones (%)'),
                                 tcUI('cri_remi'))
                 )
               ),
               hr(),
               h3('Sector Financiero'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tasas de Interés'),
                                 p('(%)'),
                                 fluidRow(tiUI('cri_ti'))),
                          column(width = 6,
                                 h5('Inversión Extranjera Directa'),
                                 p('Millones de USD$'),
                                 fluidRow(iedUI('cri_ied'))))
               ),
             )),
    tabPanel('El Salvador', 
             fluidPage(
               h3('Precios'),
               tags$div(class = 'eco-graphs',
                        h5('Índice de Precios al Consumidor'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('slv_inf'))),
               hr(),
               h3('Actividad Económica'),
               tags$div(class = 'eco-graphs',
                        h5('Índice Mensual de Actividad Económica'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('slv_imae')),
                        fluidRow(column(width = 6,
                                        h5('Producto Interno Bruto'),
                                        p('Variaciones (%)'),
                                        pibUI('slv_pib')),
                                 column(width = 6,
                                        h5('Composición del PIB'),
                                        p(''),
                                        pib_pieUI('slv_pie'))
                        )
               ),
               hr(),
               h3('Sector Externo'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tipo de Cambio Venta Nominal'),
                                 p('Variaciones (%)'),
                                 tcUI('slv_tcn')),
                          column(width = 6,
                                 h5('Remesas'),
                                 p('Millones de USD$, Variaciones (%)'),
                                 tcUI('slv_remi'))
                 )
               ),
               hr(),
               h3('Sector Financiero'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tasas de Interés'),
                                 p('(%)'),
                                 fluidRow(tiUI('slv_ti'))),
                          column(width = 6,
                                 h5('Inversión Extranjera Directa'),
                                 p('Millones de USD$'),
                                 fluidRow(iedUI('slv_ied'))))
               ),
             )),
    tabPanel('Guatemala', 
             fluidPage(
               h3('Precios'),
               tags$div(class = 'eco-graphs',
                        h5('Índice de Precios al Consumidor'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('gtm_inf'))),
               hr(),
               h3('Actividad Económica'),
               tags$div(class = 'eco-graphs',
                        h5('Índice Mensual de Actividad Económica'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('gtm_imae')),
                        fluidRow(column(width = 6,
                                        h5('Producto Interno Bruto'),
                                        p('Variaciones (%)'),
                                        pibUI('gtm_pib')),
                                 column(width = 6,
                                        h5('Composición del PIB'),
                                        p(''),
                                        pib_pieUI('gtm_pie'))
                        )
               ),
               hr(),
               h3('Sector Externo'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tipo de Cambio Venta Nominal'),
                                 p('Variaciones (%)'),
                                 tcUI('gtm_tcn')),
                          column(width = 6,
                                 h5('Remesas'),
                                 p('Millones de USD$, Variaciones (%)'),
                                 tcUI('gtm_remi'))
                 )
               ),
               hr(),
               h3('Sector Financiero'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tasas de Interés'),
                                 p('(%)'),
                                 fluidRow(tiUI('gtm_ti'))),
                          column(width = 6,
                                 h5('Inversión Extranjera Directa'),
                                 p('Millones de USD$'),
                                 fluidRow(iedUI('gtm_ied'))))
               ),
             )),
    tabPanel('Honduras', 
             fluidPage(
               h3('Precios'),
               tags$div(class = 'eco-graphs',
                        h5('Índice de Precios al Consumidor'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('hnd_inf'))),
               hr(),
               h3('Actividad Económica'),
               tags$div(class = 'eco-graphs',
                        h5('Índice Mensual de Actividad Económica'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('hnd_imae')),
                        fluidRow(column(width = 6,
                                        h5('Producto Interno Bruto'),
                                        p('Variaciones (%)'),
                                        pibUI('hnd_pib'))#,
                                 #column(width = 6,
                                  #      h5('Composición del PIB'),
                                   #     p(''),
                                    #    pib_pieUI('hnd_pie'))
                        )
               ),
               hr(),
               h3('Sector Externo'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tipo de Cambio Venta Nominal'),
                                 p('Variaciones (%)'),
                                 tcUI('hnd_tcn')),
                          column(width = 6,
                                 h5('Remesas'),
                                 p('Millones de USD$, Variaciones (%)'),
                                 tcUI('hnd_remi'))
                 )
               ),
               hr(),
               h3('Sector Financiero'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tasas de Interés'),
                                 p('(%)'),
                                 fluidRow(tiUI('hnd_ti'))),
                          column(width = 6,
                                 h5('Inversión Extranjera Directa'),
                                 p('Millones de USD$'),
                                 fluidRow(iedUI('hnd_ied'))))
               ),
             )),
    tabPanel('Panamá', 
             fluidPage(
               h3('Precios'),
               tags$div(class = 'eco-graphs',
                        h5('Índice de Precios al Consumidor'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('pnm_inf'))),
               hr(),
               h3('Actividad Económica'),
               tags$div(class = 'eco-graphs',
                        h5('Índice Mensual de Actividad Económica'),
                        p('Variaciones (%)'),
                        fluidRow(VarimUI('pnm_imae')),
                        fluidRow(column(width = 6,
                                        h5('Producto Interno Bruto'),
                                        p('Variaciones (%)'),
                                        pibUI('pnm_pib'))#,
                                 #column(width = 6,
                                  #      h5('Composición del PIB'),
                                   #     p(''),
                                    #    pib_pieUI('pnm_pie'))
                        )
               ),
               hr(),
               h3('Sector Externo'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tipo de Cambio Venta Nominal'),
                                 p('Variaciones (%)'),
                                 tcUI('pnm_tcn')),
                          column(width = 6,
                                 h5('Remesas'),
                                 p('Millones de USD$, Variaciones (%)'),
                                 tcUI('pnm_remi'))
                 )
               ),
               hr(),
               h3('Sector Financiero'),
               tags$div(
                 fluidRow(column(width = 6,
                                 h5('Tasas de Interés'),
                                 p('(%)'),
                                 fluidRow(tiUI('pnm_ti'))),
                          column(width = 6,
                                 h5('Inversión Extranjera Directa'),
                                 p('Millones de USD$'),
                                 fluidRow(iedUI('pnm_ied'))))
               ),
             ))
  )
)